# Generated by Django 4.0.3 on 2022-03-07 16:50

from django.db import migrations, models

import apps.drf_json_encoder


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(blank=True, encoder=apps.drf_json_encoder.JSONEncoder, null=True)),
                ("suspicious", models.BooleanField(default=False)),
            ],
        ),
    ]
