# Generated by Django 4.0.3 on 2022-03-05 23:36

from django.db import migrations, models

import apps.tgbot.drf_json_encoder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.CharField(max_length=32, primary_key=True, serialize=False)),
                (
                    "extra_data",
                    models.JSONField(blank=True, encoder=apps.tgbot.drf_json_encoder.JSONEncoder, null=True),
                ),
                ("has_subscription", models.BooleanField(default=False)),
                ("atms", models.ManyToManyField(blank=True, related_name="subscribers", to="monitor.atm")),
            ],
        ),
    ]
